spring:
  profiles:
    include: auth
  # JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # OAuth 2.0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <Google Client ID>
            client-secret: <Google Client Secret>
            scope:
              - email
              - profile
          github:
            client-id: <Github Client ID>
            client-secret: <Github Client Secret>
          facebook:
            client-id: <Facebook Client ID>
            client-secret: <Facebook Client Secret>
          naver:
            client-id: <Naver Client ID>
            client-secret: <Naver Client Secret>
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: <Kakao Client ID>
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: < password >
    url: jdbc:mysql://localhost:3306/springboot_blog?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.hbm2ddl.auto: update
    generate-ddl: true
    show-sql: true

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG