spring:
  profiles:
    include: auth

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # OAuth 2.0

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG